package com.csse3200.game.components.Weapons;

public enum WeaponType {
    MELEE_WRENCH,

    MELEE_KATANA,
    MELEE_BEE_STING,
    RANGED_SLINGSHOT,

    RANGED_BOOMERANG,
    RANGED_GRENADE,
    RANGED_BLUEMERANG,
    RANGED_MISSILES,
    RANGED_HOMING,
    RANGED_NUKE,

    STATIC_WEAPON,
    STICK,
    WOODHAMMER,
    STONEHAMMER,
    STEELHAMMER
}