name: Build Javadoc

on: [push, pull_request]

# Should only build javadocs - not publish to pages
jobs:
  build_jdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Checkout repo to remote machine
      - name: Set up OpenJDK17 
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build Javadoc
        run: |
          cd $GRADLE_DIR
          chmod +x ./gradlew
          ./gradlew javadoc
        env:
          GRADLE_DIR: 'source' # Modify this to wherever './gradlew' is 
